
sudo: required #needed because we are making use of Docker
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #dont display prompts requiring user input
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #command below will modify the shell
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  #allows GCP to knwo who we are and provides the credentials.
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-305620
  #specify the region of compute resources
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  #login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t djxc65/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true djxc65/react-test npm test -- --coverage

#custom deployment provider. Nothing is built in for GCP & Travis
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
