sudo: required #needed because we are making use of Docker
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #command below will modify the shell
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  #allows GCP to knwo who we are and provides the credentials.
  - gcloud auth activate-service-account --key-file service-account.json
